### PR TITLE
Support for non-ascii characters in password

### PR DESCRIPTION
**Pull request by cmordue**
This is an issue at least with node 4. The default encoding for hash.update is binary (see: https://nodejs.org/dist/v4.2.4/docs/api/crypto.html#crypto_hash_update_data_input_encoding) but for node 6, this has been changed to be utf-8 (see https://nodejs.org/dist/v6.7.0/docs/api/crypto.html#crypto_hash_update_data_input_encoding). So if you're on an old version of node, the calculated hash is incorrect.

### CODE REVIEW

**Comment by jmarca** [comment]
Awesome thanks for the pull requests.  They all looked good with very little work on my end to inspect them

I didn't know anyone but me was using this library, and in truth, I haven't used it in years.  Now that I know someone else is using it, perhaps I'll give it a once over  (I believe that I actually *learned* how to write tests in mocha with this module, hence the lame missing "done" callback!)

Anyway, thanks.

**Comment by cmordue** [comment]
thanks for pushing this out there. it's much better to collaborate with code like this than rolling my own. plus you actual have tests which was great!

**Comment by jmarca** [comment]
Quick question if you have a moment. On my end, the "verify value from slapdpasswd" test is failing.  As I said I haven't touched this in a while.  Can you confirm that it is failing on your end too?  Or it could be a node version mismatch or something.

Thanks,
James

**Comment by cmordue** [comment]
It worked for me. I'm using nodejs 4.2.4.

**Comment by jmarca** [comment]
Was failing on mine.  Can you double check that the new version doesn't fail on 4.X node?

I'm setting up a CI build thing now with multiple node versions to deal with this automatically...kids these days inventing stuff I never knew I'd need.

**Comment by cmordue** [comment]
Yep. I'll check a few versions when I'm back on a computer.

**Comment by jmarca** [comment]
No need...I got the travis CI thing working and it tests back through node 4, all tests pass. 

Again, thanks for the submissions on this.

**Comment by cmordue** [comment]
Great! Thanks for setting it up for Travis as well.

**Pull request merged**
